---
title: "Feature Selection"
author: "Kishen Sharma"
date: "4/23/2020"
output: html_document
---

```{r}
#Read in libraries
library(tidyverse)
library(xlsx)
```

```{r include=FALSE}
#Set wd 
setwd("C:/Users/kishe/Documents/Data Science/Projects/Tableau/Makeover Monday/World Development Indicators/Data/02_Cleaned_Data/")

#Read in cleaned WDID Data
wdid_df <- read.csv("20200424_Cleaned_WDIData.csv", header=TRUE)
wdid_df <- as_tibble(wdid_df)

#Set wd 
setwd("C:/Users/kishe/Documents/Data Science/Projects/Tableau/Makeover Monday/World Development Indicators/Data/01_Raw_Data/")

#Read in World Happiness data
happy_df <- read.xlsx("World_Happiness_2019.xlsx",1)
happy_df <-as_tibble(happy_df)

```

Preview WDID data
```{r}
#View data
head(wdid_df)
```

Preview World Happiness Data
```{r}
#View data
head(happy_df)
```


# Subset top/bottom 10 countries based on world happiness











Subset columns of interest pertaining to access(to resources like electricity), income, human capital income(HCI), life, literacy, population, renewable, school, poverty, satisfaction
```{r}
df %>%
  select(contains("wom"))
```


```{r}
df %>% 
  select(contains('life'))
```



